# Generated by Django 4.2.3 on 2023-09-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
    ]
