# Generated by Django 4.2.3 on 2023-09-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0004_create_room"),
    ]

    operations = [
        migrations.DeleteModel(name="Create_Room",),
    ]
