# Generated by Django 4.2.3 on 2023-09-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0005_delete_create_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testdb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
