# Generated by Django 4.2.3 on 2023-09-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0006_testdb"),
    ]

    operations = [
        migrations.DeleteModel(name="Testdb",),
    ]
